### ISSUE TITLE
module makes magisk su visible 

### ISSUE THREAD

**Issue by ammlr** [shekhawat2/RevancedYT#1]
before I installed the module, momo didn't detect root. after installing, momo detects magisk root. is there a solution
![Uploading Screenshot_2022-08-09-12-52-16-325_io.github.vvb2060.mahoshojo.jpg…]()

**Comment by ammlr** [comment]
![Screenshot_2022-08-09-12-52-16-325_io github vvb2060 mahoshojo](https://user-images.githubusercontent.com/30746607/183575172-5f472557-16f6-450c-bd11-ffc1ead0ca39.jpg)

**Comment by shekhawat2** [comment]
try installing shamiko module. and send momos app link. ill try.

**Comment by ammlr** [comment]
ok sir

momo and shamiko https://t.me/magiskalpha/517

**Comment by ammlr** [comment]
> try installing shamiko module. and send momos app link. ill try.

I have installed the shamiko module from the start

**Comment by HuskyDG** [comment]
https://github.com/revanced/revanced-cli/pull/122/commits/c10b97ef98673463eef5535eac1e1b09d518bfad

**Comment by HuskyDG** [comment]
Because the mountpoint of revanced is being detectable, and i found some banking apps are detected for this

**Comment by shekhawat2** [comment]
> [revanced/revanced-cli@c10b97e](https://github.com/revanced/revanced-cli/commit/c10b97ef98673463eef5535eac1e1b09d518bfad)

Thanks brother

**Comment by akirasup3r** [comment]
@shekhawat2 Ok Bhai

**Comment by shekhawat2** [comment]
@akirasup3r 😂

**Comment by HuskyDG** [comment]
@shekhawat2 Actually i already knew this for long because no one care to detect this. But one day, i found out that some members in my group report some banking apps and PUBG New state detect this
https://t.me/c/1740179387/18944
