### ISSUE TITLE
YT Revanced "Root Version" asks for MicroG

### ISSUE THREAD

**Issue by traversone** [shekhawat2/RevancedYT#10]
Hello!

After 18.05.40(2304211) version, the Magisk module installs fine but App does not start claiming MicroG is missing and linking to related repository.

still using old version then.

thank you

**Comment by traversone** [comment]
thank you! Actually it works well since third last version, I should have notified that. Sorry

**Comment by anyu7** [comment]
Dear developers: 
The latest 18.38.44 [Root] version once again prompts that MicroG is required.  crash

**Comment by anyu7** [comment]
Dear developers: 
The latest 18.38.44 [Root] version once again prompts that MicroG is required.  crash

**Comment by shekhawat2** [comment]
> Dear developers: The latest 18.38.44 [Root] version once again prompts that MicroG is required. crash

oh no. wait
