### ISSUE TITLE
YT Revanced "Root Version" 18.45.43 does not start

### ISSUE THREAD

**Issue by traversone** [shekhawat2/RevancedYT#11]
hello,

version released on 15/12 has a startup issue. Another question: is there any reason why the size of zip file is more than doubles in all versions released since last month (more or less) ?

thank you

**Comment by shekhawat2** [comment]
fixed both issues

**Comment by traversone** [comment]
it works flawlessly now and ZIP size got back to the usual one, many thanks Shekhawat!
