### ISSUE TITLE
There are no files to download other than source code

### ISSUE THREAD

**Issue by jaack08** [shekhawat2/RevancedYT#12]
For the recent releases there is no files in assets, so there is nothing to download other than source, many users from my group doesn't know what to do with it and a fix will help 🫡

**Comment by shekhawat2** [comment]
Ill fix it today.

**Comment by traversone** [comment]
today the issue is still there, no file to download other than source code

**Comment by shekhawat2** [comment]
> today the issue is still there, no file to download other than source code

that was i guess apkmirror server issue, re-runing it again. it will okay now.
